### ISSUE TITLE
[BODY] Separate positions for feet

### ISSUE THREAD

**Issue by FreyaIthildur** [Collaboratives/MeshbodyFeatureRequests#38]
**Is your feature request related to a problem? Please describe.**
Customers would want to use separate positions for feet

**Describe the solution you'd like**
L and R controls

**Is there an alternative solution until feature implementation?**
No.

**Comment by Collaboratives** [comment]
Duplicate of https://github.com/Collaboratives/MeshbodyFeatureRequests/issues/17
